/*
Copyright (c) 2018-present, Walmart Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//  ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Walmart.Sdk.Marketplace.V2.Payload.Order
{
    using System;
    using System.Xml.Serialization;
    using System.Collections.Generic;
    using Walmart.Sdk.Base.Primitive;

    [XmlTypeAttribute(Namespace = "http://walmart.com/mp/orders", TypeName = "elementsType")]
    [XmlRootAttribute("elements", Namespace = "http://walmart.com/mp/v3/orders", IsNullable = false)]
    public class OrderListElements : BasePayload
    {
        [XmlElement("order")]
        public List<Order> Orders { get; set; }

        /// <summary>
        /// OrdersListType class constructor
        /// </summary>
        public OrderListElements()
        {
            Orders = new List<Order>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "4.4.0.7")]
    [Serializable]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://walmart.com/mp/orders", TypeName="ordersListType")]
    [XmlRootAttribute("list", Namespace="http://walmart.com/mp/orders", IsNullable=false)]
    public class OrdersListType : BasePayload
    {
        [XmlElement("meta")]
        public MetaType Meta { get; set; }

        [XmlElement("elements")]
        public OrderListElements Elements { get; set; }
    
        /// <summary>
        /// OrdersListType class constructor
        /// </summary>
        public OrdersListType()
        {
            Elements = new OrderListElements();
            Meta = new MetaType();
        }
    }
}
