/*
Copyright (c) 2018-present, Walmart Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//  ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Walmart.Sdk.Marketplace.V2.Payload.Order
{
    using System;
    using System.Xml.Serialization;
    using System.Collections.Generic;
    using Walmart.Sdk.Base.Primitive;

    [XmlTypeAttribute(Namespace = "http://walmart.com/mp/orders",TypeName ="orderLinesType")]
    [XmlRootAttribute("orderLines", Namespace = "http://walmart.com/mp/orders", IsNullable = false)]
    public class OrderLines : BasePayload
    {
        [XmlElement("orderLine")]
        public List<OrderLineType> Lines { get; set; }

        public OrderLines()
        {
            Lines = new List<OrderLineType>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "4.4.0.7")]
    [Serializable]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://walmart.com/mp/orders")]
    [XmlRootAttribute("order", Namespace="http://walmart.com/mp/orders", IsNullable=false)]
    public class Order : BasePayload
    {
        /// <summary>
        /// General Info about this PO
        /// </summary>
        [XmlElement("purchaseOrderId")]
        public string PurchaseOrderId { get; set; }
        [XmlElement("customerOrderId")]
        public string CustomerOrderId { get; set; }
        [XmlElement("customerEmailId")]
        public string CustomerEmailId { get; set; }
        [XmlElement("orderDate")]
        public System.DateTime OrderDate { get; set; }
        [XmlElement("shippingInfo")]
        public ShippingInfoType ShippingInfo { get; set; }

        [XmlElement("orderLines", IsNullable = false)]
        public OrderLines OrderLines { get; set; }
    
        /// <summary>
        /// Order class constructor
        /// </summary>
        public Order()
        {
            OrderLines = new OrderLines();
            ShippingInfo = new ShippingInfoType();
        }
    }
}
