/*
Copyright (c) 2018-present, Walmart Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//  ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Walmart.Sdk.Marketplace.V2.Payload.Inventory
{
    using System.Xml.Serialization;
    using System.Xml;
    using Walmart.Sdk.Base.Primitive;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "4.4.0.7")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://walmart.com/")]
    [XmlRootAttribute(Namespace="http://walmart.com/", IsNullable=false)]
    public class InventoryHeader: BasePayload
    {
        /// <summary>
        /// This indicates schema version associated with the XML payload
        /// </summary>
        [XmlElement("version")]
        public InventoryHeaderVersion Version { get; set; }
        /// <summary>
        /// Date after which the offer is no longer valid
        /// The dateTime is specified in the following form "YYYY-MM-DDThh:mm:ss" where:
        /// YYYY  indicates the year
        /// MM    indicates the month
        /// DD    indicates the day
        /// T     indicates the start of the required time section
        /// hh    indicates the hour
        /// mm    indicates the minute
        /// ss    indicates the second
        /// Note: All components are required!
        /// </summary>
        [XmlElement("feedDate")]
        public System.DateTime FeedDate { get; set; }
    
        /// <summary>
        /// InventoryHeader class constructor
        /// </summary>
        public InventoryHeader()
        {
            Version = InventoryHeaderVersion.Item14;
        }
    }
}
