/*
Copyright (c) 2018-present, Walmart Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//  ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Walmart.Sdk.Marketplace.V2.Payload.Price
{
    using System.Xml.Serialization;
    using System.Xml;
    using Walmart.Sdk.Base.Primitive;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "4.4.0.7")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://walmart.com/", TypeName="pricingType")]
    [XmlRootAttribute("pricingType")]
    public class PricingType : BasePayload
    {
        /// <summary>
        /// Current price value of the item
        /// </summary>
            [XmlElement("currentPrice")]
            public Price CurrentPrice { get; set; }
        /// <summary>
        /// Current price type to indicate the type of promotion like REDUCED/CLEARANCE
        /// </summary>
            [XmlElement("currentPriceType")]
            public PriceType CurrentPriceType { get; set; }
        /// <summary>
        /// The price that the current price is compared to
        /// </summary>
            [XmlElement("comparisonPrice")]
            public Price ComparisonPrice { get; set; }
        /// <summary>
        /// Price display codes used to indicate a MAP promotion
        /// </summary>
            [XmlElement("priceDisplayCodes")]
            public PriceDisplayCodes PriceDisplayCodes { get; set; }
            [XmlAttribute(AttributeName="effectiveDate")]
            public System.DateTime EffectiveDate { get; set; }
            [XmlAttribute(AttributeName="expirationDate")]
            public System.DateTime ExpirationDate { get; set; }
            [XmlAttribute(AttributeName="promoId")]
            public string PromoId { get; set; }
            [XmlAttribute(AttributeName="processMode")]
            public ProcessModeType ProcessMode { get; set; }
    
        /// <summary>
        /// PricingType class constructor
        /// </summary>
        public PricingType()
        {
            PriceDisplayCodes = new PriceDisplayCodes();
            ComparisonPrice = new Price();
            CurrentPrice = new Price();
        }
    }
}
