/*
Copyright (c) 2018-present, Walmart Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//  ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------

using Walmart.Sdk.Base.Primitive;

namespace Walmart.Sdk.Marketplace.V2.Payload.Item
{
    using System;
    using System.Xml.Serialization;
    using System.Xml;

    /// <summary>
    /// MPItemView
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "4.4.0.7")]
    [Serializable]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://walmart.com/")]
    [XmlRootAttribute(Namespace="http://walmart.com/", ElementName = "MPItemView", IsNullable=false)]
    public class ItemView : BasePayload
    {
        [XmlElement("mart")]
        public Mart Mart { get; set; }
        [XmlElement("sku")]
        public string Sku { get; set; }
        [XmlElement("wpid")]
        public string Wpid { get; set; }
        [XmlElement("upc")]
        public string Upc { get; set; }
        [XmlElement("gtin")]
        public string Gtin { get; set; }
        [XmlElement("productName")]
        public string ProductName { get; set; }
        [XmlElement("shelf")]
        public string Shelf { get; set; }
        [XmlElement("productType")]
        public string ProductType { get; set; }
        [XmlElement("price", IsNullable = false)]
        public Money Price;
        [XmlElement("publishedStatus")]
        public ItemPublishStatus PublishedStatus { get; set; }
    
        /// <summary>
        /// MPItemView class constructor
        /// </summary>
        public ItemView()
        {
            Price = new Money();
        }
    }
}
