/*
Copyright (c) 2018-present, Walmart Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//  ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Walmart.Sdk.Marketplace.V2.Payload.Promotion
{
    using System;
    using System.Xml.Serialization;
    using System.Xml;
    using System.Collections.Generic;
    using Walmart.Sdk.Base.Primitive;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "4.4.0.7")]
    [Serializable]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlRootAttribute(Namespace="", IsNullable=false)]
    public class ServiceResponse : BasePayload
    {
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="status")]
        public Status Status { get; set; }
        [XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false, ElementName="errors")]
        public List<Error> Errors { get; set; }
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="header")]
        public ServiceHeader Header { get; set; }
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="payload")]
        public object Payload { get; set; }
    
        /// <summary>
        /// ServiceResponse class constructor
        /// </summary>
        public ServiceResponse()
        {
            Header = new ServiceHeader();
            Errors = new List<Error>();
        }
    }
}
