/*
Copyright (c) 2018-present, Walmart Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//  ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Walmart.Sdk.Marketplace.V3.Payload.Feed
{
    using System.Xml.Serialization;
    using System.Xml;
    using Walmart.Sdk.Base.Primitive;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "4.4.0.7")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://walmart.com/", TypeName="feedRecord")]
    [XmlRootAttribute("feedRecord")]
    public class FeedRecord : BasePayload
    {
        [XmlElement("feedId")]
        public string FeedId { get; set; }
        [XmlElement("feedSource")]
        public string FeedSource { get; set; }
        [XmlElement("feedType")]
        public string FeedType { get; set; }
        [XmlElement("partnerId")]
        public string PartnerId { get; set; }
        [XmlElement("partnerName")]
        public string PartnerName { get; set; }
        [XmlElement("itemsReceived")]
        public long ItemsReceived { get; set; }
        [XmlElement("itemsSucceeded")]
        public long ItemsSucceeded { get; set; }
        [XmlElement("itemsFailed")]
        public long ItemsFailed { get; set; }
        [XmlElement("itemsProcessing")]
        public long ItemsProcessing { get; set; }
        [XmlElement("feedStatus")]
        public string FeedStatus { get; set; }
        [XmlElement("feedDate")]
        public System.DateTime FeedDate { get; set; }
        [XmlElement("batchId")]
        public string BatchId { get; set; }
        [XmlElement("modifiedDtm")]
        public System.DateTime ModifiedDtm { get; set; }
        [XmlElement("fileName")]
        public string FileName { get; set; }
        [XmlElement("itemDataErrorCount")]
        public long ItemDataErrorCount { get; set; }
        [XmlElement("itemSystemErrorCount")]
        public long ItemSystemErrorCount { get; set; }
        [XmlElement("itemTimeoutErrorCount")]
        public long ItemTimeoutErrorCount { get; set; }
    }
}
