/*
Copyright (c) 2018-present, Walmart Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//  ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Walmart.Sdk.Marketplace.V3.Payload.Feed
{
    using System.Xml.Serialization;
    using System.Xml;
    using Walmart.Sdk.Base.Primitive;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "4.4.0.7")]

    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://walmart.com/")]
    [XmlRootAttribute("ItemResponse")]
    public class ItemResponse : BasePayload
    {
        /// <summary>
        /// mart where the item would be listed
        /// </summary>
            [XmlElement("mart")]
            public Mart Mart { get; set; }
        /// <summary>
        /// partner's item identifier
        /// </summary>
            [XmlElement("sku")]
            public string Sku { get; set; }
        /// <summary>
        /// Walmart's item identifier
        /// </summary>
            [XmlElement("wpid")]
            public string Wpid { get; set; }
        /// <summary>
        /// UPC
        /// </summary>
            [XmlElement("upc")]
            public string Upc { get; set; }
            [XmlElement("gtin")]
            public string Gtin { get; set; }
        /// <summary>
        /// Title of the product to be displayed on the product details page.
        /// </summary>
            [XmlElement("productName")]
            public string ProductName { get; set; }
            [XmlElement("shelf")]
            public string Shelf { get; set; }
            [XmlElement("productType")]
            public string ProductType { get; set; }
        /// <summary>
        /// current price
        /// </summary>
            [XmlElement("price")]
            public Money Price { get; set; }
        /// <summary>
        /// item publish status
        /// </summary>
            [XmlElement("publishedStatus")]
            public ItemPublishStatus PublishedStatus { get; set; }
        /// <summary>
        /// additional attributes bag, for future use
        /// </summary>
            [XmlElement("additionalAttributes")]
            public NameValueAttributes AdditionalAttributes { get; set; }
    
        /// <summary>
        /// ItemResponse class constructor
        /// </summary>
        public ItemResponse()
        {
            AdditionalAttributes = new NameValueAttributes();
            Price = new Money();
        }
    }
}
