/*
Copyright (c) 2018-present, Walmart Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//  ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Walmart.Sdk.Marketplace.V3.Payload.Feed
{
    using System.Xml.Serialization;
    using System.Xml;
    using System.Collections.Generic;
    using Walmart.Sdk.Base.Primitive;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "4.4.0.7")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://walmart.com/")]
    [XmlRootAttribute("PartnerItemIngestionStatus")]
    public class PartnerItemIngestionStatus : BasePayload
    {
        /// <summary>
        /// martId of the offer listing, 0 for the default mart for the tenant (tenant ID is in the header)
        /// </summary>
        [XmlElement("martId")]
        public int MartId { get; set; }
        /// <summary>
        /// may not be provided when SKU was not found in input data
        /// </summary>
        [XmlElement("sku")]
        public string Sku { get; set; }
        /// <summary>
        /// WPID
        /// </summary>
        [XmlElement("wpid")]
        public string Wpid { get; set; }
        /// <summary>
        /// position of the item in the feed
        /// </summary>
        [XmlElement("index")]
        public int Index { get; set; }
        [XmlElement("ingestionStatus")]
        public ItemStatus IngestionStatus { get; set; }
        /// <summary>
        /// ingestion errors
        /// </summary>
        [XmlArrayItemAttribute("ingestionError", IsNullable = false)]
        [XmlArray("ingestionErrors")]
        public List<IngestionError> IngestionErrors { get; set; }
    
        /// <summary>
        /// PartnerItemIngestionStatus class constructor
        /// </summary>
        public PartnerItemIngestionStatus()
        {
            IngestionErrors = new List<IngestionError>();
        }
    }
}
